alberthu16/100-day-coding-challenge

README.md
day3/README.md
day3/flatten.py

Please leave comments, suggestions, tips n tricks!

Day3: Flatten Binary Tree to Linked List

---

README.md
day5/README.md
day5/pathsum.py

Day5: Check if a path with sum exists in Binary Tree

---

day6/README.md
day6/bfsdfs.py

Day6: DFS/BFS

---

README.md
day7/README.md
day7/alienAlphabet.py
day7/twosum.py

Day7: Two Sum :D

---

day12/README.md
day12/writex.py

pls comment w/ compliments, constructive criticism, cleanliness tips, runtime/space analysis, anything!
thanks :)

Day 12: overwrite x's in a matrix

---

day13/README.md
day13/cruise-control.py

pls comment! :D code reviews, discussions, anything!

Day13: Google CodeJam 1B Problem A

---

day17/README.md
day17/searchMatrix.py

Please comment, critique, and discuss! :D

Day 17: Search for an integer in a matrix

---

day16/README.md

plz comment, complement, critique, and discuss anything! :D

Day 16: Spiral matrix 2

---

day15/README.md
day15/rectangleSums.py

please comment, critique, compliment, and discuss anything!

Day 15: Rectangle sums in matrix

---

day19/README.md
day19/matrixCountours.rb

please comment, critique, or discuss! The more of your thought process you include, the better! :D

Day 19: distances from 0s in a matrix (BFS)

---

day21/README.md
day21/helpingStephan.py

please comment, critique, and discuss! The more you explain your thoughts, the faster I can update / discuss / and learn :)
Thanks!

Day 21: GCD with floats on codefights

---

day22/README.md
day22/permutations.py

Please comment, critique, and discuss! The more explicit your thoughts, the faster I'll learn and be able to respond :) Thanks for your time and input.

Day 22: permutations of a distinct array of numbers

---

day23/README.md
day23/stringsRearrangement.py

Please comment, critique, and discuss! The more explicit your thoughts, the faster I'll learn and be able to respond :) Thanks for your time and input.

Day23: stringRearrangments

---

day18/README.md
day18/searchMatrix2.rb

please comment, criticize, or discuss! the more explanation of your thought processes, the better! thanks :)

Day 18: search matrix pt2 in ruby!!

---

day38/README.md
day38/heap.py

Day 38: implement a heap pt 1

---

day37/README.md
day37/topKFrequent.py

Day 37: Return top K frequent integers in an array

---

day38/README.md
day38/heap.py

Day 40: O(n) heapify

---

day38/heap.py

Didn't figure out the "efficient" way to implement `heapify`, if anyone has tips plz mention. Otherwise I might spend another day figuring that out.
Also, my `bubbleUp` and `bubbleDown` functions are atrocious. Please tear me apart / give me advice on how to clean those up. And anything else.
Thx <3

Day 39: MinHeap - finish bubbleUp and bubbleDown

---

README.md
day23/README.md
day24/README.md
day24/stringsRearrangementBacktracking.py

Please comment, critique, and discuss! The more explicit your thoughts, the faster I'll learn and be able to respond :) Thanks for your time and input.
as of 5/3 this code is not complete, unfortunately. too sleepy.

Day24: Strings Rearrangement (backtracking)

---

day25/README.md
day25/changeOfVowelsInCycle.py

please comment, criticize, and discuss! The more explicit your thoughts, the more helpful they are! 
Thanks :)

Day 25: change of vowels in cycle

---

day26/README.md
day26/endianWars.py

Day 26: endian wars

---

day27/README.md
day27/countingBinomialCoefficient.py

Day 27: pascal's triangle

---

day34/README.md
day34/validateIP.py

Day 34: validate IP address

---

day35/README.md
day35/reverseStr.py

Day 35: reverse string pt 2

---

day36/README.md
day36/longestConsecutive.py

plz comment, discuss, provide ideas, theories, code snippets.. anything helps! Thanks for reading :)

Day 36: Longest consecutive sequence (sorting?)

---

day41/README.md
day41/topKFrequent.py

Day 41: Redo topKFrequent using a heap for efficiency

---

day43/README.md
day43/maxHeap.py

Day 43: Implement MaxHeap using recursion for bubbleUp and bubbleDown

---

day48/README.md
day48/isMinHeap.py

Fixes #36 because there will be no day 49. RIP.

Day 48: check if an array is a min heap

---

day100/hi.txt

Yay the challenge is complete
